name: Terraform S3 Bucket

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      tf_working_dir: tf/s3-bucket
      var_file_path: ../../sandbox/us-east-1/s3-bucket/terraform.tfvars
      aws_region: us-east-1
      environment: sandbox
      apply_on_main: false
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}